### ISSUE TITLE
java.lang.RuntimeException: Invalid token

### ISSUE THREAD

**Issue by akamalov** [tobilg/docker-zookeeper-webui#2]
Hi, 

Tried to run it, however, getting an error.

**JSON definition file**

```
{
  "id": "zookeeper-web-ui",
  "cpus": 0.5,
  "mem": 1024,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "tobilg/zookeeper-webui:latest",
      "network": "BRIDGE",
      "portmappings": [{
                         "containerPort": 8080,
                         "protocol": "tcp"
      }],
      "privileged": false,
      "parameters": [
        {
          "key": "net",
          "value": "devnet"
        }
      ],
      "forcePullImage": false
    }
  },
  "portDefinitions": [],
  "ipAddress": {},
   "env": {
        "ZK_DEFAULT_NODE": "zk1.zk.ck.marathon.mesos:2181/"
    }
}
```

Instead of an IP address, I am using Mesos-DNS to resolve the running container.

**Error**

```
[root@mslave2 zookeepercli]# docker logs b9a
{
 :server-port 8080
 :default-node zk1.zk.ck.marathon.mesos:2181/
}
Exception in thread "main" java.lang.RuntimeException: Invalid token: zk1.zk.ck.marathon.mesos:2181/
        at clojure.lang.Util.runtimeException(Util.java:170)
        at clojure.lang.LispReader.interpretToken(LispReader.java:321)
        at clojure.lang.LispReader.read(LispReader.java:206)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1135)
        at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1069)
        at clojure.lang.LispReader.read(LispReader.java:180)
        at clojure.lang.RT.readString(RT.java:1707)
        at clojure.core$read_string.invoke(core.clj:3361)
        at zk_web.conf$load_conf_file.invoke(conf.clj:15)
        at zk_web.conf$load_conf.invoke(conf.clj:23)
        at zk_web.pages$eval2495.invoke(pages.clj:46)
        at clojure.lang.Compiler.eval(Compiler.java:6511)
        at clojure.lang.Compiler.load(Compiler.java:6952)
        at clojure.lang.RT.loadResourceScript(RT.java:359)
        at clojure.lang.RT.loadResourceScript(RT.java:350)
        at clojure.lang.RT.load(RT.java:429)
        at clojure.lang.RT.load(RT.java:400)
        at clojure.core$load$fn__4890.invoke(core.clj:5415)
        at clojure.core$load.doInvoke(core.clj:5414)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5227)
        at clojure.core$load_lib.doInvoke(core.clj:5264)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:603)
        at clojure.core$load_libs.doInvoke(core.clj:5298)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:603)
        at clojure.core$require.doInvoke(core.clj:5381)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at noir.server$load_views_ns.doInvoke(server.clj:37)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at zk_web.server$eval2007.invoke(server.clj:7)
        at clojure.lang.Compiler.eval(Compiler.java:6511)
        at clojure.lang.Compiler.load(Compiler.java:6952)
        at clojure.lang.RT.loadResourceScript(RT.java:359)
        at clojure.lang.RT.loadResourceScript(RT.java:350)
        at clojure.lang.RT.load(RT.java:429)
        at clojure.lang.RT.load(RT.java:400)
        at clojure.core$load$fn__4890.invoke(core.clj:5415)
        at clojure.core$load.doInvoke(core.clj:5414)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5227)
        at clojure.core$load_lib.doInvoke(core.clj:5264)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:603)
        at clojure.core$load_libs.doInvoke(core.clj:5298)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:603)
        at clojure.core$require.doInvoke(core.clj:5381)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at user$eval5$fn__7.invoke(form-init5077842078314925166.clj:1)
        at user$eval5.invoke(form-init5077842078314925166.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6511)
        at clojure.lang.Compiler.eval(Compiler.java:6501)
        at clojure.lang.Compiler.load(Compiler.java:6952)
        at clojure.lang.Compiler.loadFile(Compiler.java:6912)
        at clojure.main$load_script.invoke(main.clj:283)
        at clojure.main$init_opt.invoke(main.clj:288)
        at clojure.main$initialize.invoke(main.clj:316)
        at clojure.main$null_opt.invoke(main.clj:349)
        at clojure.main$main.doInvoke(main.clj:427)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
```

**Comment by tobilg** [comment]
Thanks for reporting. This should be fixed via https://github.com/tobilg/docker-zookeeper-webui/commit/9411a13aec5732697ae3ea2c49f4cb590ea50f87
